<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<body>
        <p>Respuesta automática. No responder.</p>
        <p class="MsoNormal" style=""><b style=""><span style="font-size: 12pt; color: rgb(254, 127, 0);">Logiciel Chile S.A.</span></b><span style="font-size: 10.5pt; color: black;">&nbsp; </span><b style=""><span style="font-size: 10.5pt; color: rgb(47, 84, 150);">- &nbsp;1<sup style="">st</sup> </span></b><b style=""><span style="font-size: 12pt; color: rgb(47, 84, 150);">KEMP Partner Center LATAM</span></b><span lang="ES" style="font-size: 12pt;"></span></p>
        <p class="MsoNormal" style=""><span style="font-size: 10.5pt; color: rgb(47, 84, 150);">Av. Pedro de Valdivia 5841, Macul, Santiago – Cod.Postal: 7810356</span><span style="font-size: 10.5pt; color: black;"><br style=""></span><span style="font-size: 10.5pt; color: rgb(47, 84, 150);">Oficina: <span class="Object" role="link" id="OBJ_PREFIX_DWT139_com_zimbra_phone"><a href="callto:+56.2.2694.3900" onclick="window.top.Com_Zimbra_Phone.unsetOnbeforeunload()">+56.2.2694.3900</a></span>&nbsp;<b style="">|</b> Correo: </span><u style=""></u><span lang="EN-US" style="font-size: 10.5pt; color: rgb(5, 99, 193);"><span class="Object" role="link" id="OBJ_PREFIX_DWT140_ZmEmailObjectHandler"><a href="mailto:soporte@logiciel.cl" target="_blank" style=""><span style="color: rgb(5, 99, 193);">soporte@logiciel.cl</span></a></span></span><span lang="EN-US" style="font-size: 12pt;"></span></p>
        <p class="MsoNormal" style=""><b style=""><u style=""><span lang="EN-US" style="font-size: 10.5pt; color: rgb(5, 99, 193);"><span class="Object" role="link" id="OBJ_PREFIX_DWT141_com_zimbra_url"><a href="http://www.logiciel.cl/" target="_blank" style=""><span style="color: rgb(5, 99, 193);">www.Logiciel.cl</span></a></span></span></u></b><span lang="EN-US" style="font-size: 12pt;"></span></p>
        <p class="MsoNormal" style=""><span lang="EN-US" style="font-size: 12pt;">&nbsp;</span></p>
        <p class="MsoNormal" style=""><span class="Object" role="link" id="OBJ_PREFIX_DWT397_com_zimbra_url"><span class="Object" role="link" id="OBJ_PREFIX_DWT404_com_zimbra_url"><a href="http://www.logiciel.cl/" target="_blank" style=""><span style="font-size: 12pt; color: rgb(5, 99, 193); text-decoration: none;"><img border="0" width="505" height="154" style="width: 5.2604in; height: 1.6041in;" id="Imagen_x0020_3" pnsrc="cid:image001.png@01DA398B.C668B840" alt="Pie de Correo Sin Usuario.v3" src="https://mail.logiciel.cl/service/home/~/?auth=co&amp;loc=en_US&amp;id=19272&amp;part=2"></span></a></span></span><span lang="ES" style="font-size: 12pt;"></span></p>
        <p class="MsoNormal" style=""><span style="font-size: 12pt; color: rgb(31, 73, 125);">&nbsp;</span><span lang="ES" style="font-size: 12pt;"></span></p>
        <p class="MsoNormal" style=""><span style="font-size: 10pt; color: rgb(64, 64, 64);">Este mensaje y sus archivos adjuntos son confidenciales y pueden contener información legalmente privilegiada. Si usted no es el destinatario previsto, notifíquenos inmediatamente por correo electrónico a <span class="Object" role="link" id="OBJ_PREFIX_DWT398_ZmEmailObjectHandler"><span class="Object" role="link" id="OBJ_PREFIX_DWT405_ZmEmailObjectHandler"><a href="mailto:conectado@logiciel.cl" target="_blank" style=""><span style="color: blue;">conectado@logiciel.cl</span></a></span></span> o número de teléfono: <span class="Object" role="link" id="OBJ_PREFIX_DWT399_com_zimbra_phone"><a href="callto:+56 2 2694 3900" onclick="window.top.Com_Zimbra_Phone.unsetOnbeforeunload()">+56 2 2694 3900</a></span> y elimine este mensaje y sus archivos adjuntos. No debe copiar este mensaje ni divulgar su contenido a ninguna otra persona ni usarlo para ningún propósito. Las manifestaciones y opiniones expresadas en este correo electrónico son las del remitente y no reflejan necesariamente las de Logiciel Chile S.A.</span></p>
        <p class="MsoNormal" style=""><span lang="EN-US" style="font-size: 10pt; color: rgb(237, 125, 49);">____________________________________________________________________________________</span><span lang="EN-US" style="font-size: 10pt; color: rgb(64, 64, 64);"></span></p>
        <p class="MsoNormal" style=""><span lang="EN-US" style="font-size: 10pt; color: rgb(33, 33, 33);">Disclaimer: This message and its attachments are confidential and may contain legally privileged information. If you are not the intended recipient, please notify us immediately by email at <span class="Object" role="link" id="OBJ_PREFIX_DWT400_ZmEmailObjectHandler"><span class="Object" role="link" id="OBJ_PREFIX_DWT406_ZmEmailObjectHandler"><a href="mailto:conectado@logiciel.cl" target="_blank" style=""><span style="color: blue;">conectado@logiciel.cl</span></a></span></span> or phone number: <span class="Object" role="link" id="OBJ_PREFIX_DWT401_com_zimbra_phone"><a href="callto:+56 2 2694 3900" onclick="window.top.Com_Zimbra_Phone.unsetOnbeforeunload()">+56 2 2694 3900</a></span> and delete this message and its attachments. You should not copy this message or disclose its contents to any other person or use it for any purpose. Statements and opinions expressed in this e-mail are those of the sender and do not necessarily reflect those of Logiciel Chile S.A.</span><span style=""></span></p>
        <p class="MsoNormal" style="">&nbsp;</p>
    </body>
</html>

